### ISSUE TITLE
Branch: sensors. Got error when using Simulator. Since it can't find the file scout-alpha

### ISSUE THREAD

**Issue by gijskoning** [LOBSTER-Robotics/LobsterSimulator#1]
Traceback (most recent call last):
  File "C:/Users/gikoning/Documents/Personal/LOB-star/src/execute/simulation_with_ptv.py", line 10, in <module>
    simulator = Simulator(1./10)
  File "C:\Users\gikoning\Documents\Personal\LOB-star\venv\lib\site-packages\lobster_simulator\Simulator.py", line 52, in __init__
    with resource_stream('lobster_simulator', 'data/scout-alpha.json') as f:
  File "C:\Users\gikoning\Documents\Personal\LOB-star\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\pkg_resources\__init__.py", line 1150, in resource_stream
  File "C:\Users\gikoning\Documents\Personal\LOB-star\venv\lib\site-packages\setuptools-40.8.0-py3.8.egg\pkg_resources\__init__.py", line 1584, in get_resource_stream
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\gikoning\\Documents\\Personal\\LOB-star\\venv\\lib\\site-packages\\lobster_simulator\\data\\scout-alpha.json'

**Comment by gijskoning** [comment]
Just found out that the manifest needs to be updated
